# Autogenerated by devscripts/update-version.py

<<<<<<< HEAD
__version__ = '2023.02.20.2'

RELEASE_GIT_HEAD = '22b71ecc552abf421cbc51312e731acd6a24e2c1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
