name: Release (nightly)
on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "!yt_dlp/version.py"
concurrency:
  group: release-nightly
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  prepare:
    if: vars.BUILD_NIGHTLY != ''
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pin_version_hash.outputs.version }}
      head_sha: ${{ steps.pin_version_hash.outputs.head_sha }}

    steps:
      - uses: actions/checkout@v3
      - name: Get version and hash
        id: pin_version_hash
        run: |
          echo "head_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          python devscripts/update-version.py "$(date -u +"%H%M%S")" | grep -Po "version=\d+(\.\d+){3}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      channel: nightly
    permissions:
      contents: read
      packages: write # For package cache

  publish:
    needs: [prepare, build]
    uses: ./.github/workflows/publish.yml
    secrets:
      ARCHIVE_REPO_TOKEN: ${{ secrets.ARCHIVE_REPO_TOKEN }}
    permissions:
      contents: write # for git and gh
    with:
      nightly: true
      version: ${{ needs.prepare.outputs.version }}
      target_commitish: ${{ needs.prepare.outputs.head_sha }}
