name: Pre-release
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write

jobs:
  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prune old nightly
        run: |
          gh release delete -y "nightly" || true
          git push --delete origin "nightly" || true
          sleep 5s
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create release
        run: |
          git tag "nightly"
          git push --tags origin
          gh release create -p -n "some notes" -t "1.0.1-nightly+$(date +%s)" "nightly"
        env:
          GITHUB_TOKEN: ${{ github.token }}
