name: Release
on: workflow_dispatch
permissions:
  contents: read

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      head_sha: ${{ steps.push_release.outputs.head_sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get version
        id: get-version
        run: echo "version=$(date --utc +"%Y.%m.%d")" >> "$GITHUB_OUTPUT"

      - name: Update version
        run: |
          python devscripts/update-version.py ${{ steps.get-version.outputs.version }}
          # make issuetemplates

      - name: Push to release
        id: push_release
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@example.com
          git add -u
          git commit -m "[version] update" -m "Created by: ${{ github.event.sender.login }}" -m ":ci skip all :ci run dl"
          git push origin --force ${{ github.event.ref }}:release
          echo "head_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Update master
        if: ${{ vars.PUSH_VERSION_COMMIT != '' }}
        run: git push origin ${{ github.event.ref }}

  release:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: write # for action-gh-release

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: ${{ github.repository }}/.github/workflows/build
        with:
          version: ${{ needs.prepare.outputs.version }}
      - uses: actions/download-artifact@v3

      - name: Get Changelog
        run: |
          { changelog="$(python devscripts/make_changelog.py -vv)"; } 2>&1 || true
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Make Update spec
        run: |
          echo "# This file is used for regulating self-update" >> _update_spec
          echo "lock 2022.07.18 .+ Python 3.6" >> _update_spec
      - name: Make SHA2-SUMS files
        run: |
          cd ./artifact/
          sha256sum * > ../SHA2-256SUMS
          sha512sum * > ../SHA2-512SUMS

      - name: Publish Release
        uses: yt-dlp/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: yt-dlp ${{ needs.prepare.outputs.version }}
          target_commitish: ${{ needs.prepare.outputs.head_sha }}
          body: |
            #### A description of the various files are in the [README](https://github.com/yt-dlp/yt-dlp#release-files)

            ---
            <details><summary><h3>Changelog</summary>

            ${{ env.changelog }}

            </details>
          files: |
            SHA2-256SUMS
            SHA2-512SUMS
            artifact/*
            _update_spec
