name: Pre-release
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write

jobs:
  publish_nightly:
    name: Publish nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prune old nightly
        run: |
          nightly_commit=$(git log -1 --format="%H" "nightly" -- || true)
          nightly_tag=$(git describe --contains --abbrev=0 --exclude "nightly" "${nightly_commit}" || true)
          [ "${nightly_tag}" ] && gh release delete -y "${nightly_tag}" || true
          [ "${nightly_tag}" ] && git push --delete origin "${nightly_tag}" || true
          git push --delete origin "nightly" || true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create nightly
        run: |
          nightly_tag="$(date +"%Y.%m.%d.%s")"
          git tag "nightly"
          git tag "${nightly_tag}"
          git push --tags origin
          gh release create -p -n "Nightly pre-release" -t "${nightly_tag}" "${nightly_tag}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
